### ISSUE TITLE
Game play adjustments

### ISSUE THREAD

**Issue by VanWardawg** [MouaYing/ScrollThief#49]
Adjust game play mechanics to make for a more easy and basic play for mouse and keyboard users.

**Comment by Besendorfer** [comment]
Should we wait to close this until the Xbox Controller bugs are worked out? Are there any more issues with it?

**Comment by MouaYing** [comment]
once the scroll wheel is made more sensitive, this can probably be closed

**Comment by Besendorfer** [comment]
I just made the scroll wheel more sensitive. Would you mind testing it out
to see if it is good enough? I also put caps on the camera height. Can you
let me know if those are good enough too?
