### ISSUE TITLE
Combat mechanic

### ISSUE THREAD

**Issue by MouaYing** [MouaYing/ScrollThief#61]
The player needs to be able to attack with the sword. The attacks can be chained together in a combo of up to 3 strikes. The third strike should deal more damage. The player cannot give movement input during a strike. The strikes should be swift---only about 10-15 ticks for each of the first two strikes, and 30-50 for the third.

**Comment by taftsandbakken** [comment]
Thanks for the details. I'll work on it more tonight. I was thinking of having the first swipe come from above his right shoulder and down diagonally (natural for where his sheath is), the second to come from left to right, then the last could be a stab (or perhaps top to bottom).

**Comment by MouaYing** [comment]
I was thinking the same thing for the first two strikes, and a top-to-bottom strike for the third. It shouldn't make much difference in the code though if you want to just use a 2D hit zone. It would be way easier than worrying about where the sword is at what point in the strike. I guess it might affect the width of the zones.

**Comment by taftsandbakken** [comment]
I finished with this and will close it when it's merged.
