### ISSUE TITLE
Xbox controller incompatibility

### ISSUE THREAD

**Issue by MouaYing** [MouaYing/ScrollThief#66]
Currently the ninja does not move with the Xbox controller. He only changes direction. Also, the menu only works with the right joystick. The left joystick is more intuitive to use for this (but more inconvenient to code). I don't think the Xbox controller has a button set up to attack either.

**Comment by taftsandbakken** [comment]
About the attack button, do you want to set that event check or do you just want to tell me which button to press?

**Comment by MouaYing** [comment]
I was thinking the X button. Could you implement that please?

**Comment by taftsandbakken** [comment]
Yeah, sure thing.

**Comment by taftsandbakken** [comment]
I added it, so it's part of my branch
