### ISSUE TITLE
Boss health bar not changing when boss is hurt

### ISSUE THREAD

**Issue by MouaYing** [MouaYing/ScrollThief#69]
It just stays yellow. The console says it's taking damage, but the bar isn't moving. Either it isn't really taking damage, or the bar is broken.

**Comment by Besendorfer** [comment]
I noticed that too. I did some tests and determined that the boss really
isn't taking damage. I let Taft know, and he is fixing it. I will, however,
add some code that will ensure that the health bar cannot go below 0.
