### ISSUE TITLE
health bars keep flashing bright and dim during boss fight

### ISSUE THREAD

**Issue by MouaYing** [MouaYing/ScrollThief#76]

**Comment by Besendorfer** [comment]
Hey Jon. I tried to reproduce this, but I'm not seeing it at all. Is there
something you're doing that causes it to happen?

**Comment by MouaYing** [comment]
The hearts are dim unless there is an active fireball.

**Comment by MouaYing** [comment]
This seems to only happen on my desktop. Maybe it's just my video card
